version: '3.8'

services:
  web:
    image: php:8.3-apache
    container_name: php-apache-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf

